---
# yamllint disable rule:line-length
name: mirror

# yamllint disable rule:truthy
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

env:
  REPO_NAME: saltproject-deb
  CODENAME: stable
  COMPONENTS: main
  ARCHITECTURES: arm64 amd64

jobs:
  mirror:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    outputs:
      keyring: ${{ steps.create-apt-repo.outputs.keyring }}
    steps:
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v5
      - uses: morph027/apt-repo-action@v3
        id: create-apt-repo
        with:
          repo-name: ${{ env.REPO_NAME }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          codename: ${{ env.CODENAME }}
          components: ${{ env.COMPONENTS }}
          architectures: ${{ env.ARCHITECTURES }}
          import-from-repo-url: |
            deb-amd64 https://packages.broadcom.com/artifactory/saltproject-deb stable main
            deb-arm64 https://packages.broadcom.com/artifactory/saltproject-deb stable main
      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ steps.create-apt-repo.outputs.dir }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: mirror
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
      - name: Adding summary
        run: |
          echo ':rocket:' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'curl -sfLo /etc/apt/trusted.gpg.d/${{ needs.build.outputs.keyring }}.asc ${{ steps.deploy-pages.outputs.page_url }}gpg.key' >> $GITHUB_STEP_SUMMARY
          echo 'echo "deb ${{ steps.deploy-pages.outputs.page_url }} ${{ env.CODENAME }} ${{ env.COMPONENTS }}" >/etc/apt/sources.list.d/${{ env.REPO_NAME }}.list' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
